export const FEED = [
  {
    type: 'reddit',
    id: 'm2r5k2',
    author: 'juliusthenormy',
    author_id: '3b6cit75',
    sub_id: '2r05i',
    sub_display_name: 'Minecraft',
    title: 'I just wanted to take a quick walk i swear...',
    created_at: '2021-03-11 15:22:43',
    selftext: '',
    permalink:
      '/r/Minecraft/comments/m2r5k2/i_just_wanted_to_take_a_quick_walk_i_swear/',
    url: 'https://v.redd.it/vzv1pe0mrem61',
    is_self: false,
    is_oc: false,
    is_nsfw: false,
    is_spoiler: false,
    upvotes: 3,
    ratio: 1.0,
    comments: 0,
  },
  {
    type: 'twitter',
    id: '1369934441892749314',
    user: {
      id: '428450334',
      name: 'xisumavoid',
      screen_name: 'xisumavoid',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/3566594635/4a30fa7fb71e007efcadc8633632c065_normal.png',
    },
    created_at: '2021-03-11 08:53:17',
    favorite_count: 0,
    retweet_count: 7,
    text:
      'RT @hermitcraft_: Minecraft 1.17 Snapshot 21w10a Lush Caves Are Here! https://t.co/8WAGvXvXqU @xisumavoid',
    retweeted_status: {
      type: 'twitter',
      id: '1369727519344234503',
      user: {
        id: '2733900258',
        name: 'Hermitcraft',
        screen_name: 'hermitcraft_',
        verified: false,
        profile_image_url:
          'https://pbs.twimg.com/profile_images/1169322979727159297/8Pgokman_normal.png',
      },
      created_at: '2021-03-10 19:11:03',
      favorite_count: 238,
      retweet_count: 7,
      text:
        'Minecraft 1.17 Snapshot 21w10a Lush Caves Are Here! https://t.co/8WAGvXvXqU @xisumavoid',
      retweeted_status: {},
      quoted_status: {},
      user_mentions: [
        {
          id: '428450334',
          name: 'xisumavoid',
          screen_name: 'xisumavoid',
        },
      ],
      urls: ['https://t.co/8WAGvXvXqU'],
      hashtags: [],
      medias: [],
    },
    quoted_status: {},
    user_mentions: [
      {
        id: '2733900258',
        name: 'Hermitcraft',
        screen_name: 'hermitcraft_',
      },
      {
        id: '428450334',
        name: 'xisumavoid',
        screen_name: 'xisumavoid',
      },
    ],
    urls: ['https://t.co/8WAGvXvXqU'],
    hashtags: [],
    medias: [],
  },
  {
    type: 'twitter',
    id: '1369759559615721473',
    user: {
      id: '428450334',
      name: 'xisumavoid',
      screen_name: 'xisumavoid',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/3566594635/4a30fa7fb71e007efcadc8633632c065_normal.png',
    },
    created_at: '2021-03-10 21:18:22',
    favorite_count: 233,
    retweet_count: 0,
    text:
      'New Music Blog : Vektor "Transmissions Of Chaos" (2021)\n\nhttps://t.co/X7wkxTEnT3\n\n#vektor #transmissionsofchaos https://t.co/QGDRIDxd07',
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [],
    urls: ['https://t.co/X7wkxTEnT3'],
    hashtags: ['vektor', 'transmissionsofchaos'],
    medias: [
      {
        url: 'https://pbs.twimg.com/media/EwJdDpVXAAACScR.jpg',
        type: 'photo',
      },
    ],
  },
  {
    type: 'twitter',
    id: '1369715366411272203',
    user: {
      id: '428450334',
      name: 'xisumavoid',
      screen_name: 'xisumavoid',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/3566594635/4a30fa7fb71e007efcadc8633632c065_normal.png',
    },
    created_at: '2021-03-10 18:22:46',
    favorite_count: 335,
    retweet_count: 7,
    text:
      'New Video : Minecraft 1.17 Snapshot 21w10a Lush Caves Are Here!\n\nhttps://t.co/8udz13Nfz8\n\n#minecraft #lushcaves #cliffsandcaves',
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [],
    urls: ['https://t.co/8udz13Nfz8'],
    hashtags: ['minecraft', 'lushcaves', 'cliffsandcaves'],
    medias: [],
  },
  {
    type: 'reddit',
    id: 'm2r688',
    author: 'Danchuc',
    author_id: 'axn0p96',
    sub_id: '2r05i',
    sub_display_name: 'Minecraft',
    title: 'Just made few stonebrick variants.',
    created_at: '2021-03-11 15:23:35',
    selftext: '',
    permalink:
      '/r/Minecraft/comments/m2r688/just_made_few_stonebrick_variants/',
    url: 'https://i.redd.it/shn0z16irem61.png',
    is_self: false,
    is_oc: false,
    is_nsfw: false,
    is_spoiler: false,
    upvotes: 3,
    ratio: 1.0,
    comments: 1,
  },
  {
    type: 'twitter',
    id: '1369681367890558982',
    user: {
      id: '428450334',
      name: 'xisumavoid',
      screen_name: 'xisumavoid',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/3566594635/4a30fa7fb71e007efcadc8633632c065_normal.png',
    },
    created_at: '2021-03-10 16:07:40',
    favorite_count: 192,
    retweet_count: 0,
    text:
      '@Xilefian @slicedlime What a derp... i was too mezmorized by the video! lol',
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [
      {
        id: '199272119',
        name: 'Felix "Xilefian"',
        screen_name: 'Xilefian',
      },
      {
        id: '16926230',
        name: 'slicedlime',
        screen_name: 'slicedlime',
      },
    ],
    urls: [],
    hashtags: [],
    medias: [],
  },
  {
    type: 'twitter',
    id: '1369680743308394499',
    user: {
      id: '428450334',
      name: 'xisumavoid',
      screen_name: 'xisumavoid',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/3566594635/4a30fa7fb71e007efcadc8633632c065_normal.png',
    },
    created_at: '2021-03-10 16:05:11',
    favorite_count: 324,
    retweet_count: 1,
    text: '@Xilefian @slicedlime How does one enable this? :-o',
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [
      {
        id: '199272119',
        name: 'Felix "Xilefian"',
        screen_name: 'Xilefian',
      },
      {
        id: '16926230',
        name: 'slicedlime',
        screen_name: 'slicedlime',
      },
    ],
    urls: [],
    hashtags: [],
    medias: [],
  },
  {
    type: 'twitter',
    id: '1369667789712154626',
    user: {
      id: '428450334',
      name: 'xisumavoid',
      screen_name: 'xisumavoid',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/3566594635/4a30fa7fb71e007efcadc8633632c065_normal.png',
    },
    created_at: '2021-03-10 15:13:42',
    favorite_count: 1608,
    retweet_count: 3,
    text:
      '@ThatMumboJumbo Protip - Use cheap headset from 2010! Still works like a charm :-P',
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [
      {
        id: '542139063',
        name: 'Mumbo Jumbo',
        screen_name: 'ThatMumboJumbo',
      },
    ],
    urls: [],
    hashtags: [],
    medias: [],
  },
  {
    type: 'reddit',
    id: 'eoidzv',
    author: 'Plagiatus',
    author_id: 'ifgly',
    sub_id: '2yjbi',
    sub_display_name: 'MinecraftCommands',
    title: 'Important Info (read before posting)',
    created_at: '2020-01-14 09:03:11',
    selftext:
      "I know you're here to get quick help with your command problems or to show off your cool work. Please read these few lines to get to know how to use this subreddit optimally:\n\n# Asking for help\n\n1. **FAQ?** Before you post, please check out the [common questions](https://www.reddit.com/r/MinecraftCommands/wiki/questions) (including answers) that we have in our subreddits wiki. These consist of the most common problems, and maybe your problem is already covered there in detail?\n2. **Titles:** Please put a summary/short version of your problem into the title of your post, don't just put \"I need help\" or \"help me plz\". Instead put for example \"how do I summon a zombie\" or \"unable to summon entity error\" and then provide more context on the post itself. This subreddit often shows up on google when people search for command related questions and we should really help them find the questions you might already have asked. Also, we likely know that you need help anyways, no need to put it in the title.\n3. **Flairs:** We have a wide array of flairs that you should attach to your post to make sure people know what the purpose of your thread is. It is *especially important* if you're asking for help, to flair your post with the appropriate minecraft version (for those who don't know: OG Minecraft is `Java` Version, everything else that has commands (Xbox, PE, PS4, Switch, Win10, etc) is `Bedrock`).\n4. **Version:** Whether you're helping or asking for help, *please pay attention to the stated version/state the version you're in!* You can do that through the previously mentioned Flairs, but also in addition can put it into the description of your post.\n5. **Search/Scroll down:** I know that reddit search is not the best one out there, but maybe someone else had a similar problem to yours in recent history. Try going to the new tab and scrolling down a bit or using the reddit search function to see if there might already be an answer to a question you have. *We're not going to close your thread for asking the same question someone else asked a year ago, we're not StackOverflow. But please at least take 30 seconds to look for it first.*\n6. **Upvote**: If you find an answer to a post helpful, please upvote it. This is less as a \"reward\" for the answering person but more as a way to automatically move the best answer to the top, for others that might have the same problem. Don't downvote an answer just because their attempts didn't work for you unless it's completely wrong or off topic / doesn't add anything to the conversation.\n\n# Creations\n\nPosting about your own creations is very much encouraged, but please remember the [10:1 guidelines of reddit](https://www.reddit.com/wiki/selfpromotion).\n\n# Discord\n\nWe have a big Discord Server for our community with lots of channels, ranging from dedicated help chats over general command related chats to non-command related chats. So if you want to join an active community of command and mapmaking enthusiasts and/or want to get quick help where communication is less slow *(Sometimes the devs stop by as well ;))*, click on the link and join our community discord:  \n[https://discord.gg/9wNcfsH](https://discord.gg/9wNcfsH)  \nMake sure you read the #welcome channel for the rule of the discord.",
    permalink:
      '/r/MinecraftCommands/comments/eoidzv/important_info_read_before_posting/',
    url:
      'https://www.reddit.com/r/MinecraftCommands/comments/eoidzv/important_info_read_before_posting/',
    is_self: true,
    is_oc: false,
    is_nsfw: false,
    is_spoiler: false,
    upvotes: 198,
    ratio: 1.0,
    comments: 1,
  },
  {
    type: 'twitter',
    id: '1369622111673810944',
    user: {
      id: '428450334',
      name: 'xisumavoid',
      screen_name: 'xisumavoid',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/3566594635/4a30fa7fb71e007efcadc8633632c065_normal.png',
    },
    created_at: '2021-03-10 12:12:12',
    favorite_count: 55,
    retweet_count: 0,
    text:
      '@The_T_Pearson I immediately want to slap some tacky "Old English" font over it and start a Black Metal band! XD\n\n(Great photos btw)',
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [
      {
        id: '3310997426',
        name: 'Tanner Pearson',
        screen_name: 'The_T_Pearson',
      },
    ],
    urls: [],
    hashtags: [],
    medias: [],
  },
  {
    type: 'twitter',
    id: '1369620160630435844',
    user: {
      id: '428450334',
      name: 'xisumavoid',
      screen_name: 'xisumavoid',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/3566594635/4a30fa7fb71e007efcadc8633632c065_normal.png',
    },
    created_at: '2021-03-10 12:04:27',
    favorite_count: 1,
    retweet_count: 0,
    text: '@bancho_gamer I do!',
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [
      {
        id: '1000132102850007041',
        name: 'Bancho',
        screen_name: 'bancho_gamer',
      },
    ],
    urls: [],
    hashtags: [],
    medias: [],
  },
  {
    type: 'twitter',
    id: '1369620110336528387',
    user: {
      id: '428450334',
      name: 'xisumavoid',
      screen_name: 'xisumavoid',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/3566594635/4a30fa7fb71e007efcadc8633632c065_normal.png',
    },
    created_at: '2021-03-10 12:04:15',
    favorite_count: 152,
    retweet_count: 0,
    text: '@Coelasquid @JasperBoerstra At least turn off the LED lights! lol',
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [
      {
        id: '42765016',
        name: 'Kelly Turnbull',
        screen_name: 'Coelasquid',
      },
      {
        id: '132248836',
        name: 'JAPPA',
        screen_name: 'JasperBoerstra',
      },
    ],
    urls: [],
    hashtags: [],
    medias: [],
  },
  {
    type: 'reddit',
    id: 'jqnvol',
    author: 'rxgamer10',
    author_id: 'pipad',
    sub_id: '2yjbi',
    sub_display_name: 'MinecraftCommands',
    title:
      "MCC Roundup #24, a summary of mapmaking-related stuff that's happened from October 1 to October 31",
    created_at: '2020-11-09 02:12:35',
    selftext: '',
    permalink:
      '/r/MinecraftCommands/comments/jqnvol/mcc_roundup_24_a_summary_of_mapmakingrelated/',
    url: 'https://i.redd.it/i7eslc7j74y51.png',
    is_self: false,
    is_oc: false,
    is_nsfw: false,
    is_spoiler: false,
    upvotes: 166,
    ratio: 0.99,
    comments: 7,
  },
  {
    type: 'twitter',
    id: '1367554912612196361',
    user: {
      id: '930243577',
      name: 'Sarc',
      screen_name: 'SimplySarc',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/1188136339084062722/s9yZs59e_normal.jpg',
    },
    created_at: '2021-03-04 19:17:53',
    favorite_count: 406,
    retweet_count: 4,
    text:
      "Should I open a discord group?\n\nI kinda meant to ages ago, but I'm lazy and dunno if I have the time to manage it.\n\nBut it could be kinda neat!",
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [],
    urls: [],
    hashtags: [],
    medias: [],
  },
  {
    type: 'twitter',
    id: '1367527461345497088',
    user: {
      id: '930243577',
      name: 'Sarc',
      screen_name: 'SimplySarc',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/1188136339084062722/s9yZs59e_normal.jpg',
    },
    created_at: '2021-03-04 17:28:48',
    favorite_count: 1268,
    retweet_count: 49,
    text:
      "The new Minecraft mountains are gonna be awesome!\n\nIt'll be pretty intense having to climb so high, dealing with the new freezing mechanic, fighting the Iceologer an--\n\n... oh\ud83d\ude14",
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [],
    urls: [],
    hashtags: [],
    medias: [],
  },
  {
    type: 'twitter',
    id: '1366062525335404554',
    user: {
      id: '930243577',
      name: 'Sarc',
      screen_name: 'SimplySarc',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/1188136339084062722/s9yZs59e_normal.jpg',
    },
    created_at: '2021-02-28 16:27:40',
    favorite_count: 466,
    retweet_count: 11,
    text:
      "I've been noticing an uptick in \"You should join X server!\" comments lately, which are fine, I get it's a compliment :)\n\nBut do consider, in any community, it's healthy to have a broad range of voices and personalities. Not everything has to coalesce into 1 single mega-group\u263a\ufe0f",
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [],
    urls: [],
    hashtags: [],
    medias: [],
  },
  {
    type: 'reddit',
    id: 'm2owri',
    author: 'o_witt',
    author_id: '4v75hfc4',
    sub_id: '21wb4i',
    sub_display_name: 'qualityredstone',
    title: 'bedrock signal strength memory cell',
    created_at: '2021-03-11 13:22:09',
    selftext:
      'signal strength memory cell can hold duel values on\n\n&#x200B;\n\n[https://youtu.be/f\\_du6JmPC-E](https://youtu.be/f_du6JmPC-E)',
    permalink:
      '/r/qualityredstone/comments/m2owri/bedrock_signal_strength_memory_cell/',
    url:
      'https://www.reddit.com/r/qualityredstone/comments/m2owri/bedrock_signal_strength_memory_cell/',
    is_self: true,
    is_oc: false,
    is_nsfw: false,
    is_spoiler: false,
    upvotes: 6,
    ratio: 0.88,
    comments: 1,
  },
  {
    type: 'twitter',
    id: '1365651701789822987',
    user: {
      id: '930243577',
      name: 'Sarc',
      screen_name: 'SimplySarc',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/1188136339084062722/s9yZs59e_normal.jpg',
    },
    created_at: '2021-02-27 13:15:12',
    favorite_count: 218,
    retweet_count: 7,
    text:
      'Slenderman turned out to be... much easier to deal with than I expected https://t.co/675t5ufFri',
    retweeted_status: {},
    quoted_status: {
      type: 'twitter',
      id: '1365645458916450308',
      user: {
        id: '268713587',
        name: 'Andrew (Toycat)',
        screen_name: 'ibxtoycat',
        verified: false,
        profile_image_url:
          'https://pbs.twimg.com/profile_images/1325578084641247232/ulI-0sGM_normal.jpg',
      },
      created_at: '2021-02-27 12:50:24',
      favorite_count: 777,
      retweet_count: 25,
      text:
        "In 2025 we'll all be walking around this way, I assure you https://t.co/h9YAglMmMj",
      retweeted_status: {},
      quoted_status: {},
      user_mentions: [],
      urls: [],
      hashtags: [],
      medias: [
        {
          url:
            'https://pbs.twimg.com/ext_tw_video_thumb/1365642726969114626/pu/img/KhSaHc7xj_pUS3br.jpg',
          type: 'video',
        },
      ],
    },
    user_mentions: [],
    urls: ['https://t.co/675t5ufFri'],
    hashtags: [],
    medias: [],
  },
  {
    type: 'twitter',
    id: '1355265036969627649',
    user: {
      id: '371921181',
      name: 'SethBling',
      screen_name: 'SethBling',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/1106024092610629632/q-CLH8Nv_normal.png',
    },
    created_at: '2021-01-29 21:22:19',
    favorite_count: 24,
    retweet_count: 2,
    text:
      'More Mario: the Gathering! https://t.co/pOf9FBbVjJ https://t.co/hIWUZ7WLTq',
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [],
    urls: ['https://t.co/pOf9FBbVjJ'],
    hashtags: [],
    medias: [
      {
        url: 'https://pbs.twimg.com/media/Es7eUWpU4AAoMNw.jpg',
        type: 'photo',
      },
    ],
  },
  {
    type: 'twitter',
    id: '1354926295381991426',
    user: {
      id: '371921181',
      name: 'SethBling',
      screen_name: 'SethBling',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/1106024092610629632/q-CLH8Nv_normal.png',
    },
    created_at: '2021-01-28 22:56:16',
    favorite_count: 32,
    retweet_count: 0,
    text:
      'Going live, playing more Mario: the Gathering! https://t.co/pOf9FBbVjJ https://t.co/cLnCxZGxRf',
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [],
    urls: ['https://t.co/pOf9FBbVjJ'],
    hashtags: [],
    medias: [
      {
        url: 'https://pbs.twimg.com/media/Es2qR58UcAEx7JY.jpg',
        type: 'photo',
      },
    ],
  },
  {
    type: 'reddit',
    id: 'm2otjl',
    author: 'bodzinho327',
    author_id: '41hhaohm',
    sub_id: '38iv4',
    sub_display_name: 'SciCraft',
    title: 'XP Farm',
    created_at: '2021-03-11 13:16:36',
    selftext:
      'Hello friends, I play on a server where you can use /grief command to see other player\u2019s coordinates, but it costs 1000 lvl to call this command. So, can anyone please suggest me an ark xp farm to easier and faster farm these levels? I don\u2019t care about size of this farm and just want to grief people.',
    permalink: '/r/SciCraft/comments/m2otjl/xp_farm/',
    url: 'https://www.reddit.com/r/SciCraft/comments/m2otjl/xp_farm/',
    is_self: true,
    is_oc: false,
    is_nsfw: false,
    is_spoiler: false,
    upvotes: 3,
    ratio: 1.0,
    comments: 8,
  },
  {
    type: 'twitter',
    id: '1354556468935106560',
    user: {
      id: '371921181',
      name: 'SethBling',
      screen_name: 'SethBling',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/1106024092610629632/q-CLH8Nv_normal.png',
    },
    created_at: '2021-01-27 22:26:43',
    favorite_count: 23,
    retweet_count: 1,
    text:
      'Gonna do another Mario: the Gathering draft! https://t.co/pOf9FBbVjJ https://t.co/lTt4qr7p0O',
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [],
    urls: ['https://t.co/pOf9FBbVjJ'],
    hashtags: [],
    medias: [
      {
        url: 'https://pbs.twimg.com/media/EsxZqSSVkAYmiE7.jpg',
        type: 'photo',
      },
    ],
  },
  {
    type: 'twitter',
    id: '1354192438122823680',
    user: {
      id: '371921181',
      name: 'SethBling',
      screen_name: 'SethBling',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/1106024092610629632/q-CLH8Nv_normal.png',
    },
    created_at: '2021-01-26 22:20:11',
    favorite_count: 28,
    retweet_count: 1,
    text:
      'Gonna draft Mario: the Gathering! Come play or watch! https://t.co/pOf9FBbVjJ https://t.co/8sfw3BT8Qg',
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [],
    urls: ['https://t.co/pOf9FBbVjJ'],
    hashtags: [],
    medias: [
      {
        url: 'https://pbs.twimg.com/media/EssOwgcVcAIr59s.jpg',
        type: 'photo',
      },
    ],
  },
  {
    type: 'twitter',
    id: '1352740420933980161',
    user: {
      id: '371921181',
      name: 'SethBling',
      screen_name: 'SethBling',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/1106024092610629632/q-CLH8Nv_normal.png',
    },
    created_at: '2021-01-22 22:10:23',
    favorite_count: 46,
    retweet_count: 0,
    text:
      'Gonna look back over Mario: the Gathering, and potentially draft it too! https://t.co/pOf9FBbVjJ https://t.co/1EyFDvdLwr',
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [],
    urls: ['https://t.co/pOf9FBbVjJ'],
    hashtags: [],
    medias: [
      {
        url: 'https://pbs.twimg.com/media/EsXmILlUcAAm27X.jpg',
        type: 'photo',
      },
    ],
  },
  {
    type: 'reddit',
    id: 'ktdpip',
    author: 'Dainternetdude',
    author_id: '1m2mb6as',
    sub_id: '2wfxg',
    sub_display_name: 'technicalminecraft',
    title: 'Technical Minecraft Wiki & Discord Server',
    created_at: '2021-01-08 23:40:43',
    selftext:
      "Some new technical Minecraft players have noticed that the wikia page on fandom is lacking in content, and what is there is often incorrect/outdated. A new, standalone wiki site is being developed. Check it out and feel free to contribute if you have knowledge which isn't there: [https://technicalmc.xyz/](https://technicalmc.xyz/) The developers of this wiki have set up a Discord server for communication between posters, and between devs: [https://discord.gg/FcTFg2E](https://discord.gg/FcTFg2E)\n\nA lot of people here don't seem to know about the Technical Minecraft Community Discord server, where there are different channels for sharing ideas & mechanics, help with farms & contraptions, and even sharing memes! Java and Bedrock players welcome, but be sure to read the rules before participating: [https://discord.gg/CM52CAH](https://discord.gg/CM52CAH)",
    permalink:
      '/r/technicalminecraft/comments/ktdpip/technical_minecraft_wiki_discord_server/',
    url:
      'https://www.reddit.com/r/technicalminecraft/comments/ktdpip/technical_minecraft_wiki_discord_server/',
    is_self: true,
    is_oc: false,
    is_nsfw: false,
    is_spoiler: false,
    upvotes: 68,
    ratio: 0.96,
    comments: 12,
  },
  {
    type: 'twitter',
    id: '1351673633358270465',
    user: {
      id: '371921181',
      name: 'SethBling',
      screen_name: 'SethBling',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/1106024092610629632/q-CLH8Nv_normal.png',
    },
    created_at: '2021-01-19 23:31:21',
    favorite_count: 71,
    retweet_count: 1,
    text:
      "I'm gonna try to start a new world and then kill the dragon quickly. Come watch! https://t.co/pOf9FBbVjJ https://t.co/F9fa0fN2o3",
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [],
    urls: ['https://t.co/pOf9FBbVjJ'],
    hashtags: [],
    medias: [
      {
        url: 'https://pbs.twimg.com/media/EsIQW6iVkAAS8sx.jpg',
        type: 'photo',
      },
    ],
  },
  {
    type: 'twitter',
    id: '1347307649860325378',
    user: {
      id: '371921181',
      name: 'SethBling',
      screen_name: 'SethBling',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/1106024092610629632/q-CLH8Nv_normal.png',
    },
    created_at: '2021-01-07 22:22:30',
    favorite_count: 108,
    retweet_count: 1,
    text:
      'Calculator-free speedrunning! https://t.co/pOf9FBtwIj https://t.co/F8tTWAVbyb',
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [],
    urls: ['https://t.co/pOf9FBtwIj'],
    hashtags: [],
    medias: [
      {
        url: 'https://pbs.twimg.com/media/ErKZKTyVkAEO8DW.jpg',
        type: 'photo',
      },
    ],
  },
  {
    type: 'twitter',
    id: '1346959518945562626',
    user: {
      id: '371921181',
      name: 'SethBling',
      screen_name: 'SethBling',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/1106024092610629632/q-CLH8Nv_normal.png',
    },
    created_at: '2021-01-06 23:19:09',
    favorite_count: 129,
    retweet_count: 5,
    text:
      'Gonna speedrun and try real hard not to encourage you to calculate for my where the stronghold is, based on the my coordinates and look direction as I throw eyes of ender. https://t.co/pOf9FBbVjJ https://t.co/CtSIXkt8jL',
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [],
    urls: ['https://t.co/pOf9FBbVjJ'],
    hashtags: [],
    medias: [
      {
        url: 'https://pbs.twimg.com/media/ErFciD4VoAALYuu.jpg',
        type: 'photo',
      },
    ],
  },
  {
    type: 'reddit',
    id: 'lt0efy',
    author: 'Dainternetdude',
    author_id: '1m2mb6as',
    sub_id: '2wfxg',
    sub_display_name: 'technicalminecraft',
    title: 'Frequently Asked Questions',
    created_at: '2021-02-26 16:47:27',
    selftext:
      "**Please refer to these before you post to see if your question has been answered already!**\n\n1. Q: Why doesn't my \\[insert anything technical\\] work on my server? It's a vanilla server only spigot/paper.A: Spigot is not vanilla. Paper is not vanilla. We only allow posts pertaining to vanilla. Try your thing on vanilla and if it still doesn't work there, then come here.",
    permalink:
      '/r/technicalminecraft/comments/lt0efy/frequently_asked_questions/',
    url:
      'https://www.reddit.com/r/technicalminecraft/comments/lt0efy/frequently_asked_questions/',
    is_self: true,
    is_oc: false,
    is_nsfw: false,
    is_spoiler: false,
    upvotes: 28,
    ratio: 1.0,
    comments: 7,
  },
  {
    type: 'twitter',
    id: '1346211482715885568',
    user: {
      id: '371921181',
      name: 'SethBling',
      screen_name: 'SethBling',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/1106024092610629632/q-CLH8Nv_normal.png',
    },
    created_at: '2021-01-04 21:46:43',
    favorite_count: 589,
    retweet_count: 15,
    text:
      'Speedrunning without any detectable levels of cheating! https://t.co/pOf9FBbVjJ https://t.co/JqMrdY6FJd',
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [],
    urls: ['https://t.co/pOf9FBbVjJ'],
    hashtags: [],
    medias: [
      {
        url: 'https://pbs.twimg.com/media/Eq6z_hfVEAMvCcz.jpg',
        type: 'photo',
      },
    ],
  },
  {
    type: 'twitter',
    id: '1323454540239138819',
    user: {
      id: '419232978',
      name: 'Etho',
      screen_name: 'EthoLP',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/1653150513/EthoSmall_normal.png',
    },
    created_at: '2020-11-03 02:38:45',
    favorite_count: 3084,
    retweet_count: 15,
    text:
      "Thanks for the help everyone. It seems normally they use the VP9 (best) or AV1 (medium) codec on my videos. Today they used AVC1 (fast but bad) probably because the servers couldn't keep up.",
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [],
    urls: [],
    hashtags: [],
    medias: [],
  },
  {
    type: 'twitter',
    id: '1323445593419571201',
    user: {
      id: '419232978',
      name: 'Etho',
      screen_name: 'EthoLP',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/1653150513/EthoSmall_normal.png',
    },
    created_at: '2020-11-03 02:03:12',
    favorite_count: 2990,
    retweet_count: 30,
    text:
      "Anyone know if YouTube is having compression issues lately? I haven't changed any settings but it seems to be getting worse for me. https://t.co/R3yvWOZihH",
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [],
    urls: [],
    hashtags: [],
    medias: [
      {
        url: 'https://pbs.twimg.com/media/El3R6uMVMAABwhf.jpg',
        type: 'photo',
      },
    ],
  },
  {
    type: 'twitter',
    id: '1302006248599105538',
    user: {
      id: '419232978',
      name: 'Etho',
      screen_name: 'EthoLP',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/1653150513/EthoSmall_normal.png',
    },
    created_at: '2020-09-04 22:10:54',
    favorite_count: 2505,
    retweet_count: 38,
    text:
      'The LP550 download link went down pretty quickly. Any suggestions on where I can host a 2.4 GB world without running out of traffic?',
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [],
    urls: [],
    hashtags: [],
    medias: [],
  },
  {
    type: 'twitter',
    id: '1301249358067724289',
    user: {
      id: '419232978',
      name: 'Etho',
      screen_name: 'EthoLP',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/1653150513/EthoSmall_normal.png',
    },
    created_at: '2020-09-02 20:03:17',
    favorite_count: 5969,
    retweet_count: 167,
    text:
      "/me wakes up. Goes to computer to release World Tour episode. Discovers it is still uploading... Looks like it will have to wait until tomorrow, it's a big one.",
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [],
    urls: [],
    hashtags: [],
    medias: [],
  },
  {
    type: 'twitter',
    id: '1298001622950322176',
    user: {
      id: '419232978',
      name: 'Etho',
      screen_name: 'EthoLP',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/1653150513/EthoSmall_normal.png',
    },
    created_at: '2020-08-24 20:57:57',
    favorite_count: 3906,
    retweet_count: 46,
    text:
      'It might be a late HermitCraft upload today, or else tomorrow. I had to do a reupload on it.',
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [],
    urls: [],
    hashtags: [],
    medias: [],
  },
  {
    type: 'twitter',
    id: '1284715622903844864',
    user: {
      id: '419232978',
      name: 'Etho',
      screen_name: 'EthoLP',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/1653150513/EthoSmall_normal.png',
    },
    created_at: '2020-07-19 05:04:08',
    favorite_count: 5951,
    retweet_count: 78,
    text:
      'I made some computer changes this week (New Monitor), and took a bit of a break. New HermitCraft hopefully on Monday.',
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [],
    urls: [],
    hashtags: [],
    medias: [],
  },
  {
    type: 'twitter',
    id: '1244544615945916416',
    user: {
      id: '419232978',
      name: 'Etho',
      screen_name: 'EthoLP',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/1653150513/EthoSmall_normal.png',
    },
    created_at: '2020-03-30 08:38:53',
    favorite_count: 3013,
    retweet_count: 129,
    text:
      "It's awesome having such nice and supportive viewers. Thanks everyone! https://t.co/d6AwZAhfpW",
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [],
    urls: ['https://t.co/d6AwZAhfpW'],
    hashtags: [],
    medias: [],
  },
  {
    type: 'twitter',
    id: '1209953818508550144',
    user: {
      id: '419232978',
      name: 'Etho',
      screen_name: 'EthoLP',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/1653150513/EthoSmall_normal.png',
    },
    created_at: '2019-12-25 21:47:24',
    favorite_count: 2603,
    retweet_count: 98,
    text:
      'Today I started a new Enigmatica 2 modded Minecraft series with @iskall85 . https://t.co/G5zBngZCYG Today I also tried tweeting, hope I did it right.',
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [
      {
        id: '2378426935',
        name: 'Iskall85',
        screen_name: 'iskall85',
      },
    ],
    urls: ['https://t.co/G5zBngZCYG'],
    hashtags: [],
    medias: [],
  },
  {
    type: 'twitter',
    id: '1170067814951964672',
    user: {
      id: '419232978',
      name: 'Etho',
      screen_name: 'EthoLP',
      verified: false,
      profile_image_url:
        'https://pbs.twimg.com/profile_images/1653150513/EthoSmall_normal.png',
    },
    created_at: '2019-09-06 20:14:40',
    favorite_count: 1292,
    retweet_count: 18,
    text:
      'My OBS recording messed up for the next 2 RAD episodes, so you might want to watch Pause/Beef instead.',
    retweeted_status: {},
    quoted_status: {},
    user_mentions: [],
    urls: [],
    hashtags: [],
    medias: [],
  },
];
